services:
  - type: web
    name: ivasms-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python index.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        value: "10000"
      - key: IVASMS_EMAIL
        sync: false
      - key: IVASMS_PASSWORD
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
    healthCheckPath: /
